### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by v4hn** [TAMS-Group/gpd_grasp_msgs#1]
Is there any reason why you would fork these messages (without actually forking on github)?
At least provide the URL to the original source, possibly in the github description or a README.md .

Will they not accept required changes to their messages?

**Comment by lianghongzhuo** [comment]
Because these msgs are inside gpd_ros package https://github.com/atenpas/gpd_ros
and to install  that package, we need to install gpd package. 
And gpd package depends on Caffe.
That's a bit complicated if we do not use gpd but only want use these msgs.
So I create this package.
I can add some readme to say the original source of these msgs.

**Comment by v4hn** [comment]
Makes sense unless they move their messages to a separate repository.

**Comment by v4hn** [comment]
Alternatively you could fork their package and remove all non-message contents to stay compatible.

If you actually use the new messages (with the `tams_` prefix) in your own code, we should make this a public repository though.

**Comment by lianghongzhuo** [comment]
How about remove this package and fork gpd_ros and rename it to gpd_grasp_msgs?

**Comment by v4hn** [comment]
I just filed https://github.com/atenpas/gpd_ros/issues/16

Feel free to comment there.

**Comment by lianghongzhuo** [comment]
OK, I subscribed to that issue and we can see how they reply.
